# Data
image_root: '../export/share/datasets/vision/flickr30k/'
ann_root: 'annotation'
dataset: 'flickr'

# Train
batch_size_train: 20
batch_size_test: 20
max_epoch: 6
image_size: 384
queue_size: 57600
alpha: 0.4
k_test: 128

# Checkpoint
pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_retrieval_flickr.pth'

# Vit
vit: 'small'
vit_grad_ckpt: True
vit_ckpt_layer: 4
negative_all_rank: False

# Optimizer
weight_decay: 0.05
min_lr: 0
init_lr: 0.00005
