# Data
json_root: '/datadrive/dataloader/all.json'
dataset: 'pretrain'
dataloader: 'pretrain'

#image_root: 'C:/Jonathan/DistillationResearch/dlip-work/export/share/datasets/vision/flickr30k/'
#ann_root: 'annotation'
#dataset: 'flickr'
#dataloader: 'retrieval_flickr'
#batch_size: 2

# Train
queue_size: 57600
alpha: 0.4
max_epoch: 20

# Vit
vit: 'small'
vit_grad_ckpt: False
vit_ckpt_layer: 0

# Bert
bert: 'small'
med_config: '../configs/bert-small_config.json'

image_size: 224
embed_dim: 256
batch_size: 288

# optimizer
weight_decay: 0.02
init_lr: 0.0005
min_lr: 0.000001
warmup_lr: 0.000001
lr_decay_rate: 0.9
warmup_steps: 3000


