# Data
image_root: 'C:/Jonathan/DistillationResearch/dlip-work/export/share/datasets/vision/flickr30k/'
ann_root: 'annotation'
dataset: 'flickr'
dataloader: 'retrieval_flickr'

# Train
batch_size: 16
image_size: 224
embed_dim: 256
queue_size: 57600
alpha: 0.4

# Checkpoint
checkpoint: '../save/dlip_pretrain_20.pth'

# Vit
vit: 'small'
vit_grad_ckpt: False
vit_ckpt_layer: 0

# Bert
med_config: '../configs/bert-small_config.json'
bert: 'small'

# Optimizer
weight_decay: 0.02
init_lr: 0.0005
min_lr: 0.000001
warmup_lr: 0.000001
lr_decay_rate: 0.9
max_epoch: 20
warmup_steps: 3000


